[module/i3]
    margins = 2

    type = internal/i3

    pin-workspaces = true

    fuzzy-match = true

    ws-icon-0 = 1;
    ws-icon-1 = 2;
    ws-icon-2 = 3;
    ws-icon-3 = 4;
    ws-icon-4 = 5;
    ws-icon-5 = 6;
    ws-icon-6 = 7;
    ws-icon-7 = 8;
    ws-icon-8 = 9;󰙯
    ws-icon-9 = 10;

    ws-icon-default = 󰣇

    ; Available tags:
    ;   <label-state> (default) - gets replaced with <label-(focused|unfocused|visible|urgent)>
    ;   <label-mode> (default)
    format = <label-state> <label-mode>

    ; Available tokens:
    ;   %mode%
    ; Default: %mode%
    label-mode = %mode%
    label-mode-padding = ${variables.margins}
    label-mode-background = ${colors.background-alt}

    ; Available tokens:
    ;   %name%
    ;   %icon%
    ;   %index%
    ;   %output%
    ; Default: %icon% %name%
    label-focused = %{T2}%icon% 
    label-focused-foreground = ${colors.primary}
    label-focused-background = ${colors.background-alt}
    label-focused-padding = ${variables.margins}

    label-unfocused = %{T2}%icon% 
    label-unfocused-foreground = ${colors.foreground-alt}
    label-unfocused-background = ${colors.background-alt}
    label-unfocused-padding = ${variables.margins}

    label-visible = %{T2}%icon% 
    label-visible-foreground = ${colors.primary}
    label-visible-background = ${colors.background-alt}
    label-visible-padding = ${variables.margins}

    label-urgent = %{T2}%icon% 
    label-urgent-foreground = ${colors.red}
    label-urgent-background = ${colors.background-alt}
    label-urgent-padding = ${variables.margins}

[module/xworkspaces]
    type = internal/xworkspaces

    label-active = %name%
    label-active-background = ${colors.background-alt}
    label-active-underline= ${colors.primary}
    label-active-padding = 1

    label-occupied = %name%
    label-occupied-padding = 1

    label-urgent = %name%
    label-urgent-background = ${colors.alert}
    label-urgent-padding = 1

    label-empty = %name%
    label-empty-foreground = ${colors.disabled}
    label-empty-padding = 1

[module/xwindow]
    type = internal/xwindow
    label = %class% - %title%
    label-maxlen = 30
    label-background = ${colors.background-alt}
    label-foreground = ${colors.foreground}
    label-empty = Empty
    label-empty-background = ${colors.background-alt}
    label-empty-foreground = ${colors.foreground}

    format-prefix = "  "
    format-prefix-foreground = ${colors.primary}
    format-prefix-background = ${colors.background-alt}

[module/pulseaudio]
    type = internal/pulseaudio

    format-volume-prefix = "󰕾 "
    format-volume-prefix-foreground = ${colors.primary}
    format-volume-prefix-background = ${colors.background-alt}
    format-volume = <label-volume>

    label-volume = %percentage%%
    label-volume-background = ${colors.background-alt}

    label-muted = muted
    label-muted-foreground = ${colors.disabled}
    label-muted-background = ${colors.background-alt}

[module/xkeyboard]
    type = internal/xkeyboard

    blacklist-0 = num lock
    blacklist-1 = scroll lock
    blacklist-2 = caps lock

    label-layout = %layout%
    format-prefix = "  "
    format-prefix-foreground = ${colors.primary}
    format-prefix-background = ${colors.background-alt}

    label-layout-foreground = ${colors.foreground}
    label-layout-background = ${colors.background-alt}
    label-indicator-padding = 2
    label-indicator-margin = 1

[module/memory]
    type = internal/memory
    interval = 2
    format-prefix = " "
    format-prefix-foreground = ${colors.primary}
    format-prefix-background = ${colors.background-alt}

    label-foreground = ${colors.foreground}
    label-background = ${colors.background-alt}
    label = %percentage_used:2%%

[module/cpu]
    type = internal/cpu
    interval = 2
    format-prefix = " "
    format-prefix-background = ${colors.background-alt}

    label-foreground = ${colors.foreground}
    label-background = ${colors.background-alt}
    format-prefix-foreground = ${colors.primary}
    label = %percentage:2%%

[module/clock]
    type = internal/date
    interval = 1

    date = %H:%M:%S

    format-prefix-foreground = ${colors.primary}
    format-prefix-background = ${colors.background-alt}
    format-prefix = "  "

    label = %date%
    label-foreground = ${colors.foreground}
    label-background = ${colors.background-alt}

[module/date]
    type = internal/date
    interval = 1

    date = %d.%m.%Y

    format-prefix-foreground = ${colors.primary}
    format-prefix-background = ${colors.background-alt}
    format-prefix = "  "

    label = %date%
    label-foreground = ${colors.foreground}
    label-background = ${colors.background-alt}

[module/battery]
    type = internal/battery
    time-format = %H:%M
    battery = BAT0
    adapter = ADP1

    format-charging = <animation-charging> <label-charging>
    format-discharging = <ramp-capacity> <label-discharging>
    format-charging-foreground = ${colors.primary}
    format-charging-background = ${colors.background-alt}

    format-discharging-background = ${colors.background-alt}
    format-discharging-foreground = ${colors.primary}

    label-charging =  %percentage%%
    label-discharging = %percentage%%
    label-discharging-foreground = ${colors.foreground}
    label-full = %percentage%%
    label-full-background = ${colors.background-alt}
    label-low = 󰀨 %percentage%%

    ramp-capacity-0 = 
    ramp-capacity-1 = 
    ramp-capacity-2 = 
    ramp-capacity-3 = 
    ramp-capacity-4 = 
    bar-capacity-width = 10
    animation-charging-0 = 
    animation-charging-1 = 
    animation-charging-2 = 
    animation-charging-3 = 
    animation-charging-4 = 
    animation-charging-framerate = 750
    animation-discharging-0 = 
    animation-discharging-1 = 
    animation-discharging-2 = 
    animation-discharging-3 = 
    animation-discharging-4 = 
    animation-discharging-framerate = 500
    animation-low-0 = !
    animation-low-1 =
    animation-low-framerate = 200

[module/tray]
    type = internal/tray
    format-background = ${colors.background-alt}

    tray-position = right
    tray-detached = false
    tray-background = ${colors.background-alt}
    tray-maxsize = 16
    tray-offset-x = 0
    tray-offset-y = 0
    tray-spacing = 7px
    tray-scale = 1.0

[module/lock]
    type = custom/script
    label =  
    exec = echo  
    format = <label>
    format-padding = 1 
    format-background = ${colors.background-alt}
    format-foreground = #ffffff
    click-left = exec i3lock-fancy-dualmonitor

[module/menu]
    type = custom/menu
    label-open = Apps
    label-close = x

    ; Optional item separator
    ; Default: none
    label-separator = |
    expand-right = true

    menu-0-0 = Browsers
    menu-0-0-exec = #menu-apps.open.1
    menu-0-1 = Multimedia
    menu-0-1-exec = #menu-apps.open.2

    menu-1-0 = Firefox
    menu-1-0-exec = firefox
    menu-1-1 = Chromium
    menu-1-1-exec = chromium

    menu-2-0 = Gimp
    menu-2-0-exec = gimp
    menu-2-1 = Scrot
    menu-2-1-exec = scrot
